export type Category = "job_opportunity" | "congratulations" | "industry_news" | "thought_leadership" | "personal_update" | "other"

export interface Post {
  id: string
  author: string
  authorTitle: string
  avatarInitials: string
  avatarColor: string
  category: Category
  summary: string
  originalText: string
  linkedinUrl: string
  timestamp: string
  reactions: number
  comments: number
}

export const mockPosts: Post[] = [
  {
    id: "1",
    author: "Sarah Chen",
    authorTitle: "Engineering Manager at Stripe",
    avatarInitials: "SC",
    avatarColor: "#3b82f6",
    category: "job_opportunity",
    summary: "Stripe is hiring Senior Engineers for their payments infrastructure team — remote-friendly, competitive comp.",
    originalText: "Excited to share that my team at Stripe is growing! We're looking for Senior Software Engineers to work on our core payments infrastructure. This is a remote-friendly role with excellent compensation. If you're passionate about distributed systems and financial technology, I'd love to connect. Apply via the link below or DM me directly. We move fast in interviews and genuinely care about work-life balance.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "2h ago",
    reactions: 342,
    comments: 87,
  },
  {
    id: "2",
    author: "Marcus Johnson",
    authorTitle: "CTO at Fintech Startup",
    avatarInitials: "MJ",
    avatarColor: "#10b981",
    category: "congratulations",
    summary: "Marcus announced his promotion to CTO after 3 years of leading engineering at his fintech startup.",
    originalText: "After 3 incredible years building and leading the engineering team, I'm thrilled to announce that I've been promoted to Chief Technology Officer. This journey has been nothing short of transformational. Thank you to every teammate who trusted me and pushed me to grow. The best is yet to come. 🚀",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "4h ago",
    reactions: 1204,
    comments: 215,
  },
  {
    id: "3",
    author: "Priya Nair",
    authorTitle: "AI Research Lead at Google DeepMind",
    avatarInitials: "PN",
    avatarColor: "#8b5cf6",
    category: "industry_news",
    summary: "Google DeepMind published a new paper on reasoning models showing 40% improvement in complex math benchmarks.",
    originalText: "Big news from our team at DeepMind. We just published our latest research on chain-of-thought reasoning in large language models. The results are remarkable — 40% improvement on MATH benchmark and 28% on coding tasks vs our previous models. The key insight was allowing the model to 'think out loud' with internal reasoning tokens before answering. Full paper linked below. Expect this to ship to products soon.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "5h ago",
    reactions: 2891,
    comments: 432,
  },
  {
    id: "4",
    author: "David Park",
    authorTitle: "Product Lead at Figma",
    avatarInitials: "DP",
    avatarColor: "#f59e0b",
    category: "thought_leadership",
    summary: "David argues that most startups over-invest in design tooling too early, sharing a framework for when design systems actually pay off.",
    originalText: "Hot take: Most startups build design systems too early and it kills velocity. I've watched 50+ teams do this wrong. Design systems make sense when: 1) You have 3+ product designers, 2) Engineering is spending >20% of time on UI consistency bugs, 3) You have actual brand guidelines that are stable. Before that? Just use Tailwind and a component library. Stop reinventing the wheel. Ship your product first.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "7h ago",
    reactions: 5673,
    comments: 891,
  },
  {
    id: "5",
    author: "Aisha Williams",
    authorTitle: "Head of Talent at a16z",
    avatarInitials: "AW",
    avatarColor: "#ec4899",
    category: "job_opportunity",
    summary: "a16z portfolio companies are aggressively hiring — 200+ roles across AI, crypto, and bio, many in NYC and SF.",
    originalText: "Our portfolio is hiring like crazy right now. 200+ open roles across a16z portfolio companies in AI, crypto, and bio. I personally review applications for technical roles at our early-stage companies. Highlight roles this week: AI safety researcher (SF), crypto protocol engineer (remote), biotech data scientist (NYC). DM me your background and I'll route you to the right team.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "9h ago",
    reactions: 784,
    comments: 143,
  },
  {
    id: "6",
    author: "Tom Reeves",
    authorTitle: "Founder & CEO at BuildFast",
    avatarInitials: "TR",
    avatarColor: "#0077b5",
    category: "personal_update",
    summary: "Tom shared that BuildFast hit $1M ARR just 8 months after launch, reflecting on lessons learned.",
    originalText: "We just crossed $1M ARR. 8 months after launch. I want to share what actually worked: 1) We charged from day 1, 2) We said no to 80% of feature requests, 3) We talked to 5 customers every week, every single week. What didn't work: hiring too fast, obsessing over competitors, chasing press. Build slowly, charge early, talk to customers obsessively.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "11h ago",
    reactions: 8234,
    comments: 1204,
  },
  {
    id: "7",
    author: "Elena Vasquez",
    authorTitle: "ML Engineer at OpenAI",
    avatarInitials: "EV",
    avatarColor: "#3b82f6",
    category: "congratulations",
    summary: "Elena graduated from her PhD at MIT and is joining OpenAI's alignment team this month.",
    originalText: "I defended my PhD dissertation yesterday! 5 years of work on reward modeling and AI alignment, countless late nights, two failed experiments that almost broke me — and now I'm Dr. Elena Vasquez. Starting at OpenAI's alignment team next month. To everyone who supported me: thank you from the bottom of my heart. Science is a team sport. 🎓",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "1d ago",
    reactions: 3421,
    comments: 567,
  },
  {
    id: "8",
    author: "Kevin Li",
    authorTitle: "Partner at Sequoia Capital",
    avatarInitials: "KL",
    avatarColor: "#10b981",
    category: "industry_news",
    summary: "Sequoia's annual report shows AI infrastructure investments up 300% YoY, with inference costs dropping faster than expected.",
    originalText: "Just published Sequoia's annual AI report. The numbers are staggering. AI infrastructure investments up 300% YoY. But the story is really about inference costs — they're dropping 10x faster than our models predicted 18 months ago. This changes the economics of every AI application. Companies that were 'too expensive to build' 12 months ago are now default-viable. The second wave of AI companies is just beginning.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "1d ago",
    reactions: 12043,
    comments: 2341,
  },
  {
    id: "9",
    author: "Fatima Al-Hassan",
    authorTitle: "Senior PM at Notion",
    avatarInitials: "FA",
    avatarColor: "#8b5cf6",
    category: "thought_leadership",
    summary: "Fatima shares a framework for writing product specs that engineers actually love — less 'what', more 'why' and 'constraints'.",
    originalText: "The best product spec I ever wrote was one page. The worst was 47 pages. After 8 years as a PM, here's my spec template: 1 sentence problem statement. 3 bullet user stories. 5 constraints (what NOT to build). Success metrics. Open questions. That's it. Engineers don't need a novel. They need the why, the constraints, and space to do their best work. Stop writing essays. Start writing constraints.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "1d ago",
    reactions: 9876,
    comments: 1543,
  },
  {
    id: "10",
    author: "James Okafor",
    authorTitle: "Engineering Director at Shopify",
    avatarInitials: "JO",
    avatarColor: "#f59e0b",
    category: "job_opportunity",
    summary: "Shopify is hiring 50 senior engineers for their new merchant AI features team — no office required, global hiring.",
    originalText: "Shopify is going all-in on AI for merchants and we need to grow our team fast. Looking for 50+ Senior and Staff Engineers across backend, ML, and platform. We hire globally, fully remote, and we actually mean it (I'm in Lagos, my manager is in Montreal). Interview process is 3 steps, no take-home projects, and we aim to close in under 2 weeks. If you've ever wanted to build products that empower millions of small businesses, now's the time.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "2d ago",
    reactions: 2109,
    comments: 334,
  },
  {
    id: "11",
    author: "Rachel Kim",
    authorTitle: "Design Director at Airbnb",
    avatarInitials: "RK",
    avatarColor: "#ec4899",
    category: "congratulations",
    summary: "Airbnb's design team won 3 Webby Awards this year, with Rachel's team leading the accessible booking flow project.",
    originalText: "Incredibly proud moment — our team just won 3 Webby Awards including Best UX for our accessible booking flow redesign. This project took 18 months and involved deep collaboration with disability advocates, our engineering team, and hundreds of user research sessions. Accessibility isn't a feature. It's a foundation. So grateful to work with a team that truly believes that.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "2d ago",
    reactions: 4532,
    comments: 678,
  },
  {
    id: "12",
    author: "Luca Moretti",
    authorTitle: "Founder of DevTools Weekly",
    avatarInitials: "LM",
    avatarColor: "#0077b5",
    category: "industry_news",
    summary: "The developer tools market hit $12B in 2025, with AI-powered coding assistants now used by 68% of professional developers.",
    originalText: "Published our 2025 Developer Tools Market Report. Headline: the market hit $12B, up from $7B in 2023. Most striking stat: 68% of professional developers now use AI coding assistants daily (up from 22% in 2023). Cursor is the breakout winner with 3.2M monthly active devs. GitHub Copilot still leads by volume. The surprise: 40% of developers say AI tools made them *worse* at debugging — they've lost the muscle. That's the real story.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "2d ago",
    reactions: 7654,
    comments: 1231,
  },
]

export const categoryConfig: Record<Category, { label: string; color: string; bg: string; icon: string }> = {
  job_opportunity: { label: "Job Opportunity", color: "#3b82f6", bg: "rgba(59,130,246,0.12)", icon: "Briefcase" },
  congratulations: { label: "Congrats", color: "#10b981", bg: "rgba(16,185,129,0.12)", icon: "Trophy" },
  industry_news: { label: "Industry News", color: "#f59e0b", bg: "rgba(245,158,11,0.12)", icon: "Newspaper" },
  thought_leadership: { label: "Insight", color: "#8b5cf6", bg: "rgba(139,92,246,0.12)", icon: "Lightbulb" },
  personal_update: { label: "Personal", color: "#ec4899", bg: "rgba(236,72,153,0.12)", icon: "User" },
  other: { label: "Other", color: "#6b7280", bg: "rgba(107,114,128,0.12)", icon: "Hash" },
}
