export type Category =
  | "job_opportunity"
  | "career_milestone"
  | "industry_news"
  | "thought_leadership"
  | "startup_funding"
  | "product_launch"
  | "learning_growth"
  | "event_conference"
  | "congratulations"
  | "personal_story"

export interface Post {
  id: string
  author: string
  authorTitle: string
  avatarInitials: string
  avatarColor: string
  category: Category
  summary: string
  originalText: string
  linkedinUrl: string
  timestamp: string
  reactions: number
  comments: number
}

export const mockPosts: Post[] = [
  {
    id: "1",
    author: "Sarah Chen",
    authorTitle: "Engineering Manager at Stripe",
    avatarInitials: "SC",
    avatarColor: "#3b82f6",
    category: "job_opportunity",
    summary: "Stripe is hiring Senior Engineers for their payments infrastructure team — remote-friendly, competitive comp.",
    originalText: "Excited to share that my team at Stripe is growing! We're looking for Senior Software Engineers to work on our core payments infrastructure. This is a remote-friendly role with excellent compensation. If you're passionate about distributed systems and financial technology, I'd love to connect. Apply via the link below or DM me directly. We move fast in interviews and genuinely care about work-life balance.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "2h ago",
    reactions: 342,
    comments: 87,
  },
  {
    id: "2",
    author: "Marcus Johnson",
    authorTitle: "CTO at Fintech Startup",
    avatarInitials: "MJ",
    avatarColor: "#10b981",
    category: "career_milestone",
    summary: "Marcus was promoted to CTO after 3 years of leading engineering — sharing gratitude and what's next.",
    originalText: "After 3 incredible years building and leading the engineering team, I'm thrilled to announce that I've been promoted to Chief Technology Officer. This journey has been nothing short of transformational. Thank you to every teammate who trusted me and pushed me to grow. The best is yet to come. 🚀",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "4h ago",
    reactions: 1204,
    comments: 215,
  },
  {
    id: "3",
    author: "Priya Nair",
    authorTitle: "AI Research Lead at Google DeepMind",
    avatarInitials: "PN",
    avatarColor: "#8b5cf6",
    category: "industry_news",
    summary: "Google DeepMind published a new reasoning model paper showing 40% improvement on math benchmarks.",
    originalText: "Big news from our team at DeepMind. We just published our latest research on chain-of-thought reasoning in large language models. The results are remarkable — 40% improvement on MATH benchmark and 28% on coding tasks vs our previous models. The key insight was allowing the model to 'think out loud' with internal reasoning tokens before answering. Full paper linked below. Expect this to ship to products soon.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "5h ago",
    reactions: 2891,
    comments: 432,
  },
  {
    id: "4",
    author: "David Park",
    authorTitle: "Product Lead at Figma",
    avatarInitials: "DP",
    avatarColor: "#f59e0b",
    category: "thought_leadership",
    summary: "David argues most startups build design systems too early, sharing a clear framework for when they actually pay off.",
    originalText: "Hot take: Most startups build design systems too early and it kills velocity. I've watched 50+ teams do this wrong. Design systems make sense when: 1) You have 3+ product designers, 2) Engineering is spending >20% of time on UI consistency bugs, 3) You have actual brand guidelines that are stable. Before that? Just use Tailwind and a component library. Stop reinventing the wheel. Ship your product first.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "7h ago",
    reactions: 5673,
    comments: 891,
  },
  {
    id: "5",
    author: "Aisha Williams",
    authorTitle: "Head of Talent at a16z",
    avatarInitials: "AW",
    avatarColor: "#ec4899",
    category: "job_opportunity",
    summary: "a16z portfolio companies are hiring 200+ roles across AI, crypto, and bio — DM Aisha to get routed directly.",
    originalText: "Our portfolio is hiring like crazy right now. 200+ open roles across a16z portfolio companies in AI, crypto, and bio. I personally review applications for technical roles at our early-stage companies. Highlight roles this week: AI safety researcher (SF), crypto protocol engineer (remote), biotech data scientist (NYC). DM me your background and I'll route you to the right team.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "9h ago",
    reactions: 784,
    comments: 143,
  },
  {
    id: "6",
    author: "Tom Reeves",
    authorTitle: "Founder & CEO at BuildFast",
    avatarInitials: "TR",
    avatarColor: "#0077b5",
    category: "startup_funding",
    summary: "BuildFast hit $1M ARR in 8 months — Tom shares the 3 things that worked and the 3 that didn't.",
    originalText: "We just crossed $1M ARR. 8 months after launch. I want to share what actually worked: 1) We charged from day 1, 2) We said no to 80% of feature requests, 3) We talked to 5 customers every week, every single week. What didn't work: hiring too fast, obsessing over competitors, chasing press. Build slowly, charge early, talk to customers obsessively.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "11h ago",
    reactions: 8234,
    comments: 1204,
  },
  {
    id: "7",
    author: "Elena Vasquez",
    authorTitle: "ML Engineer at OpenAI",
    avatarInitials: "EV",
    avatarColor: "#3b82f6",
    category: "career_milestone",
    summary: "Elena defended her PhD at MIT and is joining OpenAI's alignment team — 5 years of work on reward modeling.",
    originalText: "I defended my PhD dissertation yesterday! 5 years of work on reward modeling and AI alignment, countless late nights, two failed experiments that almost broke me — and now I'm Dr. Elena Vasquez. Starting at OpenAI's alignment team next month. To everyone who supported me: thank you from the bottom of my heart. Science is a team sport. 🎓",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "1d ago",
    reactions: 3421,
    comments: 567,
  },
  {
    id: "8",
    author: "Kevin Li",
    authorTitle: "Partner at Sequoia Capital",
    avatarInitials: "KL",
    avatarColor: "#10b981",
    category: "industry_news",
    summary: "Sequoia's annual report: AI infrastructure investment up 300% YoY, inference costs dropping 10x faster than expected.",
    originalText: "Just published Sequoia's annual AI report. The numbers are staggering. AI infrastructure investments up 300% YoY. But the story is really about inference costs — they're dropping 10x faster than our models predicted 18 months ago. This changes the economics of every AI application. Companies that were 'too expensive to build' 12 months ago are now default-viable. The second wave of AI companies is just beginning.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "1d ago",
    reactions: 12043,
    comments: 2341,
  },
  {
    id: "9",
    author: "Fatima Al-Hassan",
    authorTitle: "Senior PM at Notion",
    avatarInitials: "FA",
    avatarColor: "#8b5cf6",
    category: "thought_leadership",
    summary: "Fatima's 1-page spec template: problem, 3 user stories, 5 constraints, metrics. Engineers love it, essays don't work.",
    originalText: "The best product spec I ever wrote was one page. The worst was 47 pages. After 8 years as a PM, here's my spec template: 1 sentence problem statement. 3 bullet user stories. 5 constraints (what NOT to build). Success metrics. Open questions. That's it. Engineers don't need a novel. They need the why, the constraints, and space to do their best work. Stop writing essays. Start writing constraints.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "1d ago",
    reactions: 9876,
    comments: 1543,
  },
  {
    id: "10",
    author: "James Okafor",
    authorTitle: "Engineering Director at Shopify",
    avatarInitials: "JO",
    avatarColor: "#f59e0b",
    category: "job_opportunity",
    summary: "Shopify hiring 50 Senior/Staff Engineers globally for their merchant AI team — no take-home, 3-step process, closes in 2 weeks.",
    originalText: "Shopify is going all-in on AI for merchants and we need to grow our team fast. Looking for 50+ Senior and Staff Engineers across backend, ML, and platform. We hire globally, fully remote, and we actually mean it (I'm in Lagos, my manager is in Montreal). Interview process is 3 steps, no take-home projects, and we aim to close in under 2 weeks. If you've ever wanted to build products that empower millions of small businesses, now's the time.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "2d ago",
    reactions: 2109,
    comments: 334,
  },
  {
    id: "11",
    author: "Rachel Kim",
    authorTitle: "Design Director at Airbnb",
    avatarInitials: "RK",
    avatarColor: "#ec4899",
    category: "congratulations",
    summary: "Airbnb's design team won 3 Webby Awards for their accessible booking flow — 18 months of collaboration with disability advocates.",
    originalText: "Incredibly proud moment — our team just won 3 Webby Awards including Best UX for our accessible booking flow redesign. This project took 18 months and involved deep collaboration with disability advocates, our engineering team, and hundreds of user research sessions. Accessibility isn't a feature. It's a foundation. So grateful to work with a team that truly believes that.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "2d ago",
    reactions: 4532,
    comments: 678,
  },
  {
    id: "12",
    author: "Luca Moretti",
    authorTitle: "Founder of DevTools Weekly",
    avatarInitials: "LM",
    avatarColor: "#0077b5",
    category: "industry_news",
    summary: "Developer tools market hit $12B in 2025; 68% of devs use AI coding assistants daily, but 40% say it hurt their debugging skills.",
    originalText: "Published our 2025 Developer Tools Market Report. Headline: the market hit $12B, up from $7B in 2023. Most striking stat: 68% of professional developers now use AI coding assistants daily (up from 22% in 2023). Cursor is the breakout winner with 3.2M monthly active devs. GitHub Copilot still leads by volume. The surprise: 40% of developers say AI tools made them *worse* at debugging — they've lost the muscle. That's the real story.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "2d ago",
    reactions: 7654,
    comments: 1231,
  },
  {
    id: "13",
    author: "Nina Patel",
    authorTitle: "Co-founder at HealthAI",
    avatarInitials: "NP",
    avatarColor: "#06b6d4",
    category: "startup_funding",
    summary: "HealthAI raised $18M Series A led by General Catalyst to bring AI diagnostics to underserved rural hospitals.",
    originalText: "Today we're announcing HealthAI's $18M Series A led by General Catalyst. We started this company because 60% of rural hospitals lack specialist access. Our AI diagnostics platform has already helped 12,000 patients get faster diagnoses. This round lets us expand to 200 more hospitals by end of 2025. Incredibly grateful to our team, investors, and every doctor who gave us a chance. The mission is just getting started.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "3h ago",
    reactions: 5421,
    comments: 892,
  },
  {
    id: "14",
    author: "Alex Thompson",
    authorTitle: "Developer Advocate at Vercel",
    avatarInitials: "AT",
    avatarColor: "#a855f7",
    category: "product_launch",
    summary: "Vercel launched AI SDK 4.0 with streaming tool calls, multi-step agents, and a new vision API — free for all plans.",
    originalText: "We just shipped Vercel AI SDK 4.0 and I'm incredibly excited about what's new: streaming tool calls (finally!), native multi-step agent support, a new vision API for image understanding, and 40% smaller bundle size. Everything you need to build production AI apps in Next.js. Available now on all plans including free. Full changelog in the comments.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "6h ago",
    reactions: 3201,
    comments: 445,
  },
  {
    id: "15",
    author: "Jordan Lee",
    authorTitle: "Staff Engineer at Meta",
    avatarInitials: "JL",
    avatarColor: "#f97316",
    category: "learning_growth",
    summary: "Jordan shares 5 system design patterns they wish they'd learned earlier — includes real examples from Meta's infrastructure.",
    originalText: "5 system design patterns I wish I'd learned at the start of my career: 1) Circuit Breakers — stop cascading failures before they take down everything. 2) Saga Pattern — distributed transactions without distributed locks. 3) CQRS — separate read/write models for scale. 4) Sidecar Pattern — decouple cross-cutting concerns. 5) Outbox Pattern — guaranteed message delivery. Each one took me years to discover through painful production incidents. Sharing so you don't have to.",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "8h ago",
    reactions: 11203,
    comments: 2103,
  },
  {
    id: "16",
    author: "Maria Santos",
    authorTitle: "Community Lead at AWS",
    avatarInitials: "MS",
    avatarColor: "#eab308",
    category: "event_conference",
    summary: "AWS re:Invent 2025 announced for Dec 1-5 in Las Vegas — early bird tickets open, CFP deadline is August 15.",
    originalText: "AWS re:Invent 2025 is officially announced! Dec 1-5, Las Vegas. Early bird pricing is open now (save $400). If you want to speak, the CFP closes August 15 — we're especially looking for talks on AI/ML in production, sustainability in cloud, and real customer case studies. I'll be there all week running the community lounge. Come say hi!",
    linkedinUrl: "https://linkedin.com/feed",
    timestamp: "12h ago",
    reactions: 2341,
    comments: 312,
  },
]

export const categoryConfig: Record<Category, { label: string; color: string; gradient: string; bg: string; icon: string; description: string }> = {
  job_opportunity:   { label: "Job Opportunity",   color: "#3b82f6", gradient: "from-blue-500 to-blue-700",    bg: "rgba(59,130,246,0.10)",  icon: "Briefcase",  description: "Hiring posts & open roles" },
  career_milestone:  { label: "Career Milestone",  color: "#10b981", gradient: "from-emerald-500 to-teal-600", bg: "rgba(16,185,129,0.10)",  icon: "TrendingUp", description: "Promotions, new roles, PhDs" },
  industry_news:     { label: "Industry News",     color: "#f59e0b", gradient: "from-amber-500 to-orange-500", bg: "rgba(245,158,11,0.10)",  icon: "Newspaper",  description: "Market & research updates" },
  thought_leadership:{ label: "Insight",           color: "#8b5cf6", gradient: "from-violet-500 to-purple-700",bg: "rgba(139,92,246,0.10)",  icon: "Lightbulb",  description: "Frameworks & hot takes" },
  startup_funding:   { label: "Startup & Funding", color: "#06b6d4", gradient: "from-cyan-500 to-blue-500",   bg: "rgba(6,182,212,0.10)",   icon: "Rocket",     description: "Funding rounds & ARR milestones" },
  product_launch:    { label: "Product Launch",    color: "#f97316", gradient: "from-orange-500 to-red-500",  bg: "rgba(249,115,22,0.10)",  icon: "Zap",        description: "New products & features" },
  learning_growth:   { label: "Learning & Growth", color: "#a855f7", gradient: "from-purple-500 to-pink-500", bg: "rgba(168,85,247,0.10)",  icon: "BookOpen",   description: "Tips, lessons & tutorials" },
  event_conference:  { label: "Events",            color: "#eab308", gradient: "from-yellow-500 to-amber-500",bg: "rgba(234,179,8,0.10)",   icon: "Calendar",   description: "Conferences & meetups" },
  congratulations:   { label: "Congrats",          color: "#ec4899", gradient: "from-pink-500 to-rose-500",   bg: "rgba(236,72,153,0.10)",  icon: "Trophy",     description: "Celebrating achievements" },
  personal_story:    { label: "Personal Story",    color: "#64748b", gradient: "from-slate-500 to-gray-600",  bg: "rgba(100,116,139,0.10)", icon: "Heart",      description: "Personal journeys & reflections" },
}
